# Generated by Django 4.2.3 on 2023-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('userimage', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
