# Generated by Django 4.2.3 on 2023-09-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_tbl_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='status',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
