# Generated by Django 4.2.3 on 2023-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_tbl_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('resturantname', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('authorizedperson', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('staff', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('status', models.CharField(default=None, max_length=200)),
            ],
            options={
                'db_table': 'tbl_resturant',
            },
        ),
    ]
