# Generated by Django 4.2.3 on 2023-09-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_tbl_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_resturant',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
