# Generated by Django 4.2.3 on 2023-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_alter_tbl_resturant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('accounttype', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_accounts',
            },
        ),
    ]
