# Generated by Django 4.2.3 on 2023-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_tbl_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.CharField(max_length=30)),
                ('MenuName', models.CharField(max_length=30)),
                ('cusine', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_foodMenu',
            },
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
