# Generated by Django 4.2.3 on 2023-09-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0007_tbl_foodmenu_alter_tbl_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_foodmenu',
            old_name='MenuName',
            new_name='menuname',
        ),
    ]
