# Generated by Django 4.2.3 on 2023-10-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Res_id',
            new_name='Res_name',
        ),
    ]
