# Generated by Django 4.2.3 on 2023-10-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0011_rename_res_id_offer_res_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='Res_name',
        ),
    ]
