# Generated by Django 4.2.3 on 2023-10-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0012_remove_offer_res_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('MenuItemName', models.CharField(max_length=30)),
                ('resturantname', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('totalamount', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
